{
 "title": "Cost Report",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "promdatasource", "label": "Prometheus Datasource", "query": "prometheus" },
   { "name": "cwdatasource", "label": "Croudwatch Datasource", "query": "cloudwatch" },
   { "name": "region", "query": "eu-west-1" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster (Global)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "On Demand Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc (\n  sum by (label_beta_kubernetes_io_instance_type) (kube_node_labels{label_eks_amazonaws_com_capacity_type=\"ON_DEMAND\"})\n)"
    }
   ]
  },
  {
   "title": "Spot Instance Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc (\n  sum by (label_beta_kubernetes_io_instance_type) (kube_node_labels{label_eks_amazonaws_com_capacity_type=\"SPOT\"})\n)"
    }
   ]
  },
  {
   "title": "Total Daily Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  sum_over_time(\n    (\n    capacity_instance:spot_instance_cost:cost \n    OR \n    capacity_instance:on_demand_instance_cost:cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Idle Daily Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum_over_time(\n    (\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:spot_idle_cpu_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:on_demand_idle_cpu_cost\n      OR\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:spot_idle_mem_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:on_demand_idle_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Usage Daily Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  sum (\n  \n      # See description for label_replace\n      label_replace(\n        zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n        OR\n        capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n      , \"resource\", \"CPU\", \"\",\"\")\n      \n      OR \n      \n      label_replace(\n        zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n        OR\n        capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n      , \"resource\", \"memory\", \"\",\"\")\n\n)\n[1d:1h])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shared Daily Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (\n  sum_over_time(\n    (\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:spot_shared_cpu_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:on_demand_shared_cpu_cost\n          OR\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:spot_shared_mem_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:on_demand_shared_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Underutilization Daily Cluster Cost",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time(\n  sum (\n  \n      # See description for label_replace\n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n              - \n              zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n          ) > 0)\n      , \"resource\", \"CPU\", \"\",\"\")\n      \n      OR \n      \n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n              -\n              zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n          ) > 0)\n      , \"resource\", \"memory\", \"\",\"\")\n\n)\n[1d:1h])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Monthly PV Cost ",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes/1024/1024/1024))",
     "legendFormat": "{{persistentvolumeclaim}}"
    },
    {
     "expr": "sum(sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes/1024/1024/1024) * 0.089)"
    }
   ]
  },
  {
   "title": "Daily Cluster Cost per Instance Type and Capacity Type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum_over_time(\n    (    \n    capacity_instance:spot_instance_cost:cost \n    OR \n    capacity_instance:on_demand_instance_cost:cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Daily Cluster Cost per Instance and Capacity Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum_over_time(\n  (\n    capacity_instance:spot_instance_cost:cost OR capacity_instance:on_demand_instance_cost:cost\n  )\n[1d:1h])",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    },
    {
     "expr": "sum(\n  sum_over_time(\n    (\n    capacity_instance:spot_instance_cost:cost OR capacity_instance:on_demand_instance_cost:cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Daily Idle Cost per Instance Type and Capacity Type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n    sum_over_time(\n      (\n        zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:spot_idle_cpu_cost\n        OR\n        capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:on_demand_idle_cpu_cost\n        OR\n        zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:spot_idle_mem_cost\n        OR\n        capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:on_demand_idle_mem_cost\n      )\n    [1d:1h])\n)\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Daily Idle Cost per Instance and Capacity Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n  sum_over_time(\n    (\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:spot_idle_cpu_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:on_demand_idle_cpu_cost\n      OR\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:spot_idle_mem_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:on_demand_idle_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    },
    {
     "expr": "sum (\n  sum_over_time(\n    (\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:spot_idle_cpu_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_cpu_price:on_demand_idle_cpu_cost\n      OR\n      zone_capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:spot_idle_mem_cost\n      OR\n      capacity_instance_node_resource:kube_node_status_allocatable_idle_instance_mem_price:on_demand_idle_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Daily Underutilization Cost per Instance Type and Capacity Type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc (\n  sum_over_time(\n      sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n      \n\t      # See description for label_replace\n\t      label_replace(\n\t          ((\n\t              zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n\t              - \n\t              zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n\t          ) > 0)\n\t          OR\n\t          ((\n\t              capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n\t              -\n\t              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n\t          ) > 0)\n\t      , \"resource\", \"CPU\", \"\",\"\")\n\t      \n\t      OR \n\t      \n\t      label_replace(\n\t          ((\n\t              zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n\t              -\n\t              zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n\t          ) > 0)\n\t          OR\n\t          ((\n\t              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n\t              -\n\t              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n\t          ) > 0)\n\t      , \"resource\", \"memory\", \"\",\"\")\n\n    )\n  [1d:1h])\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Daily Underutilization Cost per Instance Type and Capacity Type",
   "type": "timeseries",
   "description": "label_replace is used to ALWAYS have a different label (resource) when doing OR, so that no time series is filtered by binary operations (capacity_type for internal OR, resource for external OR)\n\nIf for example a pod has CPU requests but not memory requests, the binary sum (+) will filter the CPU sum (won't count for them)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "expr": "sum_over_time(\n  sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n  \n      # See description for label_replace\n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n              - \n              zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n          ) > 0)\n      , \"resource\", \"CPU\", \"\",\"\")\n      \n      OR \n      \n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n              -\n              zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n          ) > 0)\n      , \"resource\", \"memory\", \"\",\"\")\n\n)\n[1d:1h])",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    },
    {
     "expr": "sum_over_time(\n  sum (\n  \n      # See description for label_replace\n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n              - \n              zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n          ) > 0)\n      , \"resource\", \"CPU\", \"\",\"\")\n      \n      OR \n      \n      label_replace(\n          ((\n              zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n              -\n              zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n          ) > 0)\n          OR\n          ((\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n              -\n              capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n          ) > 0)\n      , \"resource\", \"memory\", \"\",\"\")\n\n)\n[1d:1h])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Daily Shared Cost per Instance Type and Capacity Type",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\n  sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n    sum_over_time(\n      (\n            zone_capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:spot_shared_cpu_cost\n            OR\n            capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:on_demand_shared_cpu_cost\n            OR\n            zone_capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:spot_shared_mem_cost\n            OR\n            capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:on_demand_shared_mem_cost\n      )\n    [1d:1h])\n  )\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    }
   ]
  },
  {
   "title": "Daily Shared Cost per Instance and Capacity Type",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "targets": [
    {
     "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) (\n  sum_over_time(\n    (\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:spot_shared_cpu_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:on_demand_shared_cpu_cost\n          OR\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:spot_shared_mem_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:on_demand_shared_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "{{label_beta_kubernetes_io_instance_type}}-{{label_eks_amazonaws_com_capacity_type}}"
    },
    {
     "expr": "sum (\n  sum_over_time(\n    (\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:spot_shared_cpu_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_cpu_price:on_demand_shared_cpu_cost\n          OR\n          zone_capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:spot_shared_mem_cost\n          OR\n          capacity_instance_node_resource:kube_node_status_shared_instance_mem_price:on_demand_shared_mem_cost\n    )\n  [1d:1h])\n)",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster (Namespace)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Daily Resources Requests Cost per Namespace",
     "type": "barchart",
     "description": "label_replace is used to ALWAYS have a different label (resource) when doing OR, so that no time series is filtered by binary operations (capacity_type for internal OR, resource for external OR)\n\nIf for example a pod has CPU requests but not memory requests, the binary sum (+) will filter the CPU sum (won't count for them)",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n    sum by (namespace) (\n        # See description for label_replace\n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n        , \"resource\", \"CPU\", \"\",\"\")\n        \n        OR \n        \n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n        , \"resource\", \"memory\", \"\",\"\")\n\n\t)\n[1d:1h])"
      }
     ]
    },
    {
     "title": "Daily Usage Cost per Namespace ",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n    sum by (namespace) (\n        # See description for label_replace\n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n        , \"resource\", \"CPU\", \"\",\"\")\n        \n        OR \n        \n        label_replace(\n\t\t    zone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n            OR\n            capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n        , \"resource\", \"memory\", \"\",\"\")\n\n\t)\n[1d:1h])"
      }
     ]
    },
    {
     "title": "Daily Resources Requests Memory Cost per Namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sort_desc(\n\tsum_over_time(\n\t\tsum by (namespace) (\n\n\t\t\tzone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost\n\t\t\tOR\n\t\t\tcapacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost\n\n\t\t)\n\t[1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Daily Memory Usage Cost per Namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sort_desc(\n\tsum_over_time(\n\t\tsum by (namespace) (\n\n\t\t\tzone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost\n\t\t\tOR\n\t\t\tcapacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost\n\n\t\t)\n\t[1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Daily Resources Requests CPU Cost per Namespace",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sort_desc(\n\tsum_over_time(\n\t\tsum by (namespace) (\n\n\t\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost\n\t\t\tOR\n\t\t\tcapacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost\n\n\t\t)\n\t[1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Daily CPU Usage Cost per Namespace ",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sort_desc(\n\tsum_over_time(\n\t\tsum by (namespace) (\n\n\t\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost\n\t\t\tOR\n\t\t\tcapacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost\n\n\t\t)\n\t[1d:1h])\n)"
      }
     ]
    },
    {
     "title": "Monthly PVCs Cost",
     "type": "barchart",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (namespace) (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes/1024/1024/1024) * 0.089)"
      }
     ]
    },
    {
     "title": "Monthly PVCs Cost",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum by (namespace) (sum by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes/1024/1024/1024) * 0.089)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Namespace / Instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (\n  sum by (node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$namespace\"}) \n  * on (node) group_left(label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) \n  sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (kube_node_labels{job=\"kube-state-metrics\"}) \n)",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{node}}"
      }
     ]
    },
    {
     "title": "Memory Usage Per Instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (\n\tsum by (node) (container_memory_working_set_bytes{namespace=~\"$namespace\", name!=\"\"})\n\t* on (node) group_left(label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) \n\tsum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (kube_node_labels{job=\"kube-state-metrics\"})\n)",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{node}} "
      }
     ]
    },
    {
     "title": "Daily CPU Usage Cost Per Instance and Capacity Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}}"
      },
      {
       "expr": "sum_over_time(\n  sum (\n    zone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost{namespace=\"$namespace\"}\n    OR\n    capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost{namespace=\"$namespace\"}\n  )\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily Memory Usage Cost Per Instance and Capacity Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily CPU Requested Cost Per Instance and Capacity Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily Memory Requested Cost Per Instance and Capacity Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Monthly PV Cost Per Namespace",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "(((sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$namespace\"}) )/1024/1024/1024) * 0.089)",
       "legendFormat": "{{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pod Per Namespace",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, pod) (\n    sum by (pod, node) (node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\"})\n    * on (node) group_left(label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) \n    sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (kube_node_labels{job=\"kube-state-metrics\"})\n)",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}}"
      }
     ]
    },
    {
     "title": "Memory Usage Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, pod) (\n  sum by (pod, node) (container_memory_working_set_bytes{namespace=\"$namespace\", name!=\"\"})\n  * on (node) group_left(label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type) \n  sum by (label_eks_amazonaws_com_capacity_type, label_beta_kubernetes_io_instance_type, node) (kube_node_labels{job=\"kube-state-metrics\"})\n)",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}} "
      }
     ]
    },
    {
     "title": "Daily CPU Usage Cost Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type, pod) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:spot_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_usage_instance_cpu_price:on_demand_pod_cpu_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily Memory Usage Cost Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type, pod) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:spot_pod_mem_usage_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_usage_instance_mem_price:on_demand_pod_mem_usage_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily CPU Requested Cost Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type, pod) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:spot_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_cpu_requests_instance_cpu_price:on_demand_pod_cpu_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Daily Memory Requested Cost Per Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "expr": "sum_over_time(\n\tsum by (label_beta_kubernetes_io_instance_type, label_eks_amazonaws_com_capacity_type, pod) (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "{{label_beta_kubernetes_io_instance_type}} - {{label_eks_amazonaws_com_capacity_type}} - {{pod}}"
      },
      {
       "expr": "sum_over_time(\n\tsum (\n\n\t\tzone_capacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:spot_pod_mem_requests_cost{namespace=\"$namespace\"}\n\t\tOR\n\t\tcapacity_instance_namespace_node_pod:pod_memory_requests_instance_mem_price:on_demand_pod_mem_requests_cost{namespace=\"$namespace\"}\n\n\t)\n[1d:1h])",
       "legendFormat": "Total"
      }
     ]
    },
    {
     "title": "Monthly PV Cost Per Pod",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024)",
       "legendFormat": "{{persistentvolumeclaim}}"
      },
      {
       "expr": "sum by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=~\"${namespace}\"}/1024/1024/1024) * 0.089"
      }
     ]
    }
   ]
  }
 ]
}